version: '3.3'
services:
        django_proj:
                build: .
                container_name: django_test
                command: python manage.py runserver 0.0.0.0:8000
                volumes: 
                        - .:/usr/src/app
                ports:
                        - "8000:8000"
                depends_on:
                        - pgdb
        
        pgdb:
                image: postgres
                container_name: pgdb_djangoTest
                environment:
                        - POSTGRES_DB=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres

